services:
  postgres:
    image: postgres:17
    container_name: smart-ride-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: smart-ride
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: smart-ride
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: